const assert = require('node:assert/strict');
const { create, confirm } = require('../jam-model.js');
const names = ['أحمد', 'علي', 'عمر', 'سعيد'];
const base = create(names, 'الواجب الأول', 'البقرة 1\nالبقرة 2\nالبقرة 3\nالبقرة 4', 'one');
assert.equal(base.confirmations.length, 0);
assert.throws(() => create(names, 'ناقص', 'آية واحدة', 'bad'));
assert.throws(() => create(names, 'مكرر', '1\n1\n2\n3', 'bad'));
assert.throws(() => confirm(base, 'علي', 0, {role:'student',name:'أحمد'}));
const first = confirm(base, 'أحمد', 0, {role:'professor'});
assert.equal(base.confirmations.length, 0);
assert.throws(() => confirm(first, 'أحمد', 1, {role:'student',name:'أحمد'}));
assert.throws(() => confirm(first, 'علي', 0, {role:'student',name:'أحمد'}));
assert.throws(() => confirm(first, 'غريب', 1, {role:'student',name:'أحمد'}));
assert.throws(() => confirm(first, 'علي', -1, {role:'student',name:'أحمد'}));
const second = confirm(first, 'علي', 1, {role:'student',name:'أحمد'});
// Earlier green students remain able to validate after another student turns green.
const third = confirm(second, 'عمر', 2, {role:'student',name:'أحمد'});
const fourth = confirm(third, 'سعيد', 3, {role:'student',name:'علي'});
assert.equal(fourth.confirmations.length, 4);
assert.equal(new Set(fourth.confirmations.map(c => c.verseIndex)).size, 4);
assert.equal(create(names, 'جديد', '1\n2\n3\n4', 'two').confirmations.length, 0);
console.log('✓ واجب الجمع: first approval, all green validators, unique verses/students, independent assignments');
const { weeklyWindow, active, current, ensureWeek } = require('../jam-model.js');
const schedule = {number:45,startDate:'2026-09-05',timeZone:'Europe/Paris'};
const before = new Date('2026-09-12T03:59:59Z');
const boundary = new Date('2026-09-12T04:00:00Z');
assert.equal(weeklyWindow(schedule,before).number,45);
assert.equal(weeklyWindow(schedule,boundary).number,46);
// Calendar weeks remain stable across the autumn DST change.
assert.equal(weeklyWindow(schedule,new Date('2026-10-31T05:00:00Z')).number,53);
let history = ensureWeek({},names,schedule,before);
const id45 = weeklyWindow(schedule,before).id;
history[id45] = {...base,...history[id45],verses:base.verses};
history[id45] = confirm(history[id45],'أحمد',0,{role:'professor'},before);
assert.equal(current(history,schedule,before).id,id45);
assert.equal(current(history,schedule,boundary),null);
assert.equal(active(history[id45],boundary),false);
assert.throws(() => confirm(history[id45],'علي',1,{role:'student',name:'أحمد'},boundary),/لا يوجد استدراك/);
const next = ensureWeek(history,names,schedule,boundary);
assert.equal(next[id45].confirmations.length,1);
assert.equal(current(next,schedule,boundary).number,46);
assert.equal(current(next,schedule,boundary).confirmations.length,0);
assert.deepEqual(current(next,schedule,boundary).verses,names.map((_,index) => `الآية ${index+1}`));
assert.equal(ensureWeek(next,names,schedule,boundary),next);
assert.equal(ensureWeek({},names,null,before).constructor,Object);
console.log('✓ Weekly Jam: 45→46 at Paris 06:00, no catch-up, clean new week, history preserved, DST');

const emptyWeek = {...next, 'week-2026-09-12': {...next['week-2026-09-12'], verses: []}};
assert.equal(ensureWeek(emptyWeek,names,schedule,boundary)['week-2026-09-12'].verses.length,names.length);
assert.equal(ensureWeek(next,names,schedule,boundary),next);
